Update The Project With Goodies
ionixjunior/Xalendar pull request #31
Opened 2020-10-05 15:27 UTC by khalidabuhakmeh

- Can now `dotnet pack Xalendar.View.csproj` to create NuGet Package
- Readme.md is updated with quick start and screenshots
- Logo and Icon for Xalendar
- `global.json` to constrain to .NET Core app 3.1

 #hacktoberfest

**Note: You will need to create a NuGet account and upload the NuGet Package from running `dotnet pack`**

You can upload and version manually for now.

2020-10-06 02:11 UTC, ionixjunior requested changes
Hi @khalidabuhakmeh. Thank you for your PR! The logo is amazing 🤩

I added some comments in the review. Could you make these adjustments?

2020-10-06 12:43 UTC, khalidabuhakmeh commented on README.md
> +Xalender is a calendar view for Xamarin.Forms applications.
```suggestion
![Xalendar logo](./assets/logo.png)

Xalendar is a calendar view for Xamarin.Forms applications.
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on README.md
> +Install Xalander using NuGet with the following command line to your shared library project.
```suggestion
Install Xalendar using NuGet with the following command line to your shared library project.
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on README.md
> +> dotnet add package Xalender
```suggestion
> dotnet add package Xalendar
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on README.md
> +To use the Xalender component, you'll need to add the following namespace to the top of your XAML views.
```suggestion
To use the Xalendar component, you'll need to add the following namespace to the top of your XAML views.
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on src/Xalendar.View/Xalendar.View.csproj
> +    <PackageId>Xalendar</PackageId>
```suggestion
    <PackageId> Xalendar</PackageId>
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on src/Xalendar.View/Xalendar.View.csproj
> +    <Title>Xalander - Xamarin.Forms Calendar</Title>
```suggestion
    <Title>Xalendar - Xamarin.Forms Calendar</Title>
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on src/Xalendar.View/Xalendar.View.csproj
> +    <Authors>Pedro Jesus</Authors>
```suggestion
    <Authors>Souza Junior</Authors>
```

2020-10-06 12:43 UTC, khalidabuhakmeh commented on src/Xalendar.View/Xalendar.View.csproj
> +    <Copyright>2020 Pedro Jesus</Copyright>
```suggestion
    <Copyright>2020 Souza Junior</Copyright>
```

2020-10-06 12:46 UTC, khalidabuhakmeh commented
Well... that was embarrassing. I never claimed to be the world's best speller 🤣.

I believe I've resolved all the errors. Feel free to `Squash and merge`

2020-10-06 19:09 UTC, ionixjunior commented
@khalidabuhakmeh haha nice, thank you!

I'll merge it at Thursday during my next live streaming. I'm developing this library every Thursdays at 7 o'clock PM EDT in my YouTube and Twitch channel. Feel free to join us! 

https://www.youtube.com/ionixjunior
https://www.twitch.tv/ionixjunior

2020-10-08 23:45 UTC, ionixjunior approved these changes
Nice! Thank you!

2020-10-08 23:46 UTC, merged